# Generated by Django 6.0.2 on 2026-02-24 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('Django Engineer', 'Django Engineer'), ('React Engineer', 'React Engineer')], max_length=100)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
